Update files on 2023-02-07 at 10:37:55

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,11 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Check if node is installed
+if ! command -v node &> /dev/null
+then
+    echo "node could not be found"
+    exit
+fi
+
 npm test
